"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { collection, doc, getDoc, getDocs, query, where } from "firebase/firestore";
import { ArrowLeft, ClipboardList, Loader2 } from "lucide-react";
import AdminGuard from "@/components/AdminGuard";
import { db } from "@/lib/firebase/client";

type Attempt = { id: string; mockId?: string; type?: string; section?: string; score?: number; total?: number; status?: string; date?: string; answers?: Record<string, string>; questionId?: string; selectedOption?: string; chapter?: string };
type Profile = { name?: string; displayName?: string; email?: string };
const score = (item: Attempt) => Number(item.score || 0);
const title = (item: Attempt) => item.type === "full" ? "Full mock" : item.section ? `${item.section} sectional` : "Mock";

function Progress({ params }: { params: Promise<{ userId: string }> }) {
  const [userId, setUserId] = useState(""); const [profile, setProfile] = useState<Profile | null>(null); const [mocks, setMocks] = useState<Attempt[]>([]); const [daily, setDaily] = useState<Attempt[]>([]); const [practice, setPractice] = useState<Attempt[]>([]); const [pyq, setPyq] = useState<Attempt[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { params.then(value => setUserId(value.userId)); }, [params]);
  useEffect(() => { if (!userId) return; Promise.all([getDoc(doc(db, "profiles", userId)), getDocs(query(collection(db, "attempts"), where("userId", "==", userId))), getDocs(query(collection(db, "daily_attempts"), where("userId", "==", userId))), getDocs(query(collection(db, "practice_attempts"), where("userId", "==", userId))), getDocs(query(collection(db, "pyq_attempts"), where("userId", "==", userId)))]).then(([p, m, d, practiceRows, pyqRows]) => { setProfile(p.exists() ? p.data() as Profile : null); setMocks(m.docs.map(row => ({ id: row.id, ...row.data() }) as Attempt).filter(row => row.status === "submitted")); setDaily(d.docs.map(row => ({ id: row.id, ...row.data() }) as Attempt)); setPractice(practiceRows.docs.map(row => ({ id: row.id, ...row.data() }) as Attempt)); setPyq(pyqRows.docs.map(row => ({ id: row.id, ...row.data() }) as Attempt)); }).catch(console.error).finally(() => setLoading(false)); }, [userId]);
  const sections = useMemo(() => ["VARC", "DILR", "QA"].map(section => mocks.filter(item => item.type === "sectional" && String(item.section || "").toUpperCase() === section)), [mocks]);
  const name = profile?.name || profile?.displayName || profile?.email || "Student";
  if (loading) return <div className="flex min-h-[50vh] items-center justify-center"><Loader2 className="animate-spin text-brand"/></div>;
  return <div className="mx-auto max-w-5xl px-4 py-10 sm:px-6"><Link href="/admin/students" className="inline-flex items-center gap-1 text-sm font-semibold text-brand-darker"><ArrowLeft size={16}/> Student Data</Link><h1 className="mt-4 font-display text-3xl font-bold">{name}</h1><p className="mt-1 text-sm text-muted">{profile?.email || "No email on profile"}</p><section className="mt-7 grid gap-3 sm:grid-cols-3">{sections.map((items, index) => <Summary key={index} label={["VARC sectional", "DILR sectional", "QA sectional"][index]} attempts={items}/>)}</section><section className="mt-6"><Summary label="Daily targets" attempts={daily}/></section><section className="mt-8 rounded-2xl border border-border bg-white p-5"><h2 className="font-display text-lg font-semibold">Submitted test details</h2><div className="mt-4 divide-y divide-border">{[...mocks, ...daily].map(item => <div key={item.id} className="py-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><b>{item.date ? `${item.date} · ${String(item.section || "").toUpperCase()} daily target` : title(item)}</b><b className="text-brand-darker">{score(item)}/{Number(item.total || 0) * 3}</b></div><p className="mt-1 text-muted">{Object.keys(item.answers || {}).length} answers recorded</p></div>)}{!mocks.length && !daily.length && <p className="py-4 text-sm text-muted">N/A — no submitted tests or daily targets.</p>}</div></section><AnswerList label="Chapter practice answers" rows={practice}/><AnswerList label="Topic-wise PYQ answers" rows={pyq}/></div>;
}
function Summary({ label, attempts }: { label: string; attempts: Attempt[] }) { const values = attempts.map(score); return <div className="rounded-2xl border border-border bg-white p-4"><p className="font-semibold">{label}</p><p className="mt-3 text-xl font-bold">{attempts.length ? `${attempts.length} attempted` : "N/A"}</p><p className="mt-1 text-sm text-muted">{values.length ? `Best ${Math.max(...values)} · Avg ${(values.reduce((sum, value) => sum + value, 0) / values.length).toFixed(1)}` : "No attempts"}</p></div>; }
function AnswerList({ label, rows }: { label: string; rows: Attempt[] }) { return <section className="mt-6 rounded-2xl border border-border bg-white p-5"><h2 className="flex items-center gap-2 font-display text-lg font-semibold"><ClipboardList size={18} className="text-brand"/>{label}</h2><div className="mt-4 divide-y divide-border">{rows.map(row => <div key={row.id} className="py-3 text-sm"><b>{row.chapter || "Question"}</b><p className="mt-1 text-muted">Question {row.questionId || "N/A"} · Answer: {row.selectedOption || "N/A"}</p></div>)}{!rows.length && <p className="py-3 text-sm text-muted">N/A — no answers submitted.</p>}</div></section>; }
export default function StudentProgressPage({ params }: { params: Promise<{ userId: string }> }) { return <AdminGuard><Progress params={params}/></AdminGuard>; }
